### ISSUE TITLE
Request Update Rest In Pawn v1.3.0

### ISSUE THREAD

**Issue by estiawan** [CrazyHackGUT/Discord#13]
hello Kruzya, there is update from Rest In Pawn v1.3.0 `Deprecated HTTPClient methodmap`. would you update it?

thanks

**Comment by estiawan** [comment]
and about this https://github.com/CrazyHackGUT/Discord/blob/master/addons/sourcemod/scripting/discord/Events.sp#L86 maybe it should be updated to discord.com?

**Comment by CrazyHackGUT** [comment]
I guess now it should be updated and ready for RiP v1.3.0.
![spcomp](https://user-images.githubusercontent.com/12576822/122678610-995c7500-d1f8-11eb-9d25-54fe26853503.png)
But requires a testing.

**Comment by estiawan** [comment]
Thank you! I will test it on my server

**Comment by estiawan** [comment]
running fine without any problem on my server

**Comment by CrazyHackGUT** [comment]
Then closed.

**Comment by estiawan** [comment]
sorry @CrazyHackGUT, my bad. i found error that you need to add `hRequest.SetHeader("Content-Type", "application/json");` on https://github.com/CrazyHackGUT/Discord/blob/master/addons/sourcemod/scripting/discord/UTIL.sp#L336
