### ISSUE TITLE
Discord_BindWebHook is not working

### ISSUE THREAD

**Issue by estiawan** [CrazyHackGUT/Discord#16]
looks like Discord_BindWebHook is not working, it doesn't add **damage_logs** in **sourcemod/configs/Discord.cfg**

My Code :
```
public void OnMapStart()
{
    Discord_BindWebHook("damage_logs", "https://discord.com/api/webhooks/857219091xxxxx/xxxxx");
}
```

**Comment by CrazyHackGUT** [comment]
This is don't should add webhook into config. It just adds to internal data structure.

**Comment by estiawan** [comment]
ohh thanks for the explanation.
