### ISSUE TITLE
Ошибка компиляции

### ISSUE THREAD

**Issue by tengzl33t** [CrazyHackGUT/Discord#5]
Не компилируется через scripting/compile.exe, стоит SM 1.10
![default](https://user-images.githubusercontent.com/10462726/45087608-2f3db880-b10f-11e8-9993-fb3c5f560e3b.PNG)

**Comment by CrazyHackGUT** [comment]
Посмотрел.
Идиоты из разрабов SB++ (_по другому я их уже назвать минимум год и не могу, смотря на всё то, что они делают_) зачем-то перепилили инклуд-файл на новый синтаксис. Чисто поэтому собираться не будет.
Сделать дополнительную поддержку новых инклуд я не могу: сразу рипнется поддержка старых, которых ещё больше. Мне этого пока не надо.
Можете у себя локально поменять на строке 163 `int` на `void`. Тогда заработает.

**Comment by tengzl33t** [comment]
изменил void на int и добавил .inc, и все скомпилировалось, спасибо
